services:
  db:
    image: postgres:16-alpine
    container_name: notism-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: notismadmin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: notism_db
    restart: unless-stopped

  api:
    image: ${API_IMAGE}
    container_name: notism-api
    ports:
      - "5000:5000"
    env_file:
      - .env.api
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
    name: notism-pgdata
