name: Prepare Environment
description: Emit prod environment context.

outputs:
  environment:
    description: GitHub environment name
    value: prod
  dotnet-env:
    description: ASPNETCORE_ENVIRONMENT value
    value: Production

runs:
  using: composite
  steps:
    - name: Noop
      shell: bash
      run: 'true'
