aws_region         = "ap-northeast-1"
environment        = "staging"
name_suffix        = "-staging"
vpc_cidr           = "10.1.0.0/16"
public_subnet_cidr = "10.1.1.0/24"
key_name           = "notism-api"
